---
- name: "Install postgresql"
  become: true
  when: funkwhale_database_managed
  package:
    name:
      - postgresql
      - python3-psycopg2

- name: "Start Postgresql"
  when: funkwhale_database_managed
  service:
    name: postgresql
    state: started

- name: "Create {{ funkwhale_database_name }} database"
  become: true
  become_user: postgres
  when: funkwhale_database_managed
  postgresql_db:
    name: "{{ funkwhale_database_name }}"
    encoding: UTF-8

- name: "Create {{ funkwhale_database_user }} database user"
  become: true
  become_user: postgres
  when: funkwhale_database_managed
  postgresql_user:
    db: "{{ funkwhale_database_name }}"
    name: "{{ funkwhale_database_user }}"

- name: "Grant privileges on database {{ funkwhale_database_name }} to {{ funkwhale_database_user }} user"
  when: funkwhale_database_managed
  become: true
  become_user: postgres
  command: psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ funkwhale_database_name }} TO {{ funkwhale_database_user }}"


- name: "Create db extensions"
  when: funkwhale_database_managed
  become: true
  become_user: postgres
  command: psql {{ funkwhale_database_name }} -c "CREATE EXTENSION IF NOT EXISTS {{ item }}"
  with_items:
    - unaccent
    - citext
