---
- name: "Install system packages"
  become: true
  package:
    name:
      - "python3"
      - "python3-dev"
      - "python3-pip"
      - "python3-venv"
      - "libldap2-dev"
      - "libsasl2-dev"
      - "git"
      - "unzip"
      - "build-essential"
      - "ffmpeg"
      - "libjpeg-dev"
      - "libmagic-dev"
      - "libpq-dev"
      - "postgresql-client"
