---
- name: "Install system packages"
  become: true
  package:
    name:
      - "python3-3_3"
      - "py38-pip-20.3.4"
      - "py38-certbot-1.22.0,1"
      - "py38-ldap3-2.8.1"
      - "py38-django-auth-ldap-4.0.0"
      #- "python3-virtualenv"
      #- "libldap2-dev"
      #- "libsasl2-dev"
      - "git"
      - "unzip"
      #- "build-essential"
      - "ffmpeg"
      #- "make"
      #- "libjpeg-dev"
      #- "libmagic-dev"
      #- "libpq-dev"
      - "postgresql13-client-13.6"
      # Needed to build cryptography wheel sometimes
      #- libssl-dev
      #- libffi-dev
      # not strictly needed but useful
      #- "curl"
      #- "dbus"
      #- "virtualenv"
      - "libxslt-1.1.35_2"
      - "rust-1.59.0"
      - "py38-libxml2-2.9.13_4"
      - "py38-Jinja2-3.0.1"
