---
- name: "Install redis"
  become: true
  when: funkwhale_redis_managed
  package:
    name:
      - redis-6.2.6

- name: "Start redis-server"
  when: funkwhale_redis_managed
  service:
    name: redis
    state: started
