---

- name: "Create {{ funkwhale_systemd_service_name }}-* systemd file"
  become: true
  template:
    src: "funkwhale-process.service.j2"
    dest: "/etc/systemd/system/{{ funkwhale_systemd_service_name }}-{{ item.name }}.service"
    mode: 0600
  with_items:
    - name: worker
      description: Funkwhale celery worker
      command: "{{ funkwhale_install_path }}/virtualenv/bin/celery -A funkwhale_api.taskapp worker -l INFO"
    - name: server
      description: Funkwhale application server
      command: "{{ funkwhale_install_path }}/virtualenv/bin/daphne -b ${FUNKWHALE_API_IP} -p ${FUNKWHALE_API_PORT} config.asgi:application --proxy-headers"
    - name: beat
      description: Funkwhale celery beat process
      command: "{{ funkwhale_install_path }}/virtualenv/bin/celery -A funkwhale_api.taskapp beat -l INFO"
  notify:
    - restart funkwhale

- name: "Create {{ funkwhale_systemd_service_name }} systemd target file"
  become: true
  template:
    src: "{{ funkwhale_systemd_service_name }}.target.j2"
    dest: "/etc/systemd/system/{{ funkwhale_systemd_service_name }}.target"
    mode: 0600
  notify:
    - restart funkwhale

- name: "Start and enable {{ funkwhale_systemd_service_name }}-* services"
  when: funkwhale_nginx_managed
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
    state: started
  with_items:
    - "{{ funkwhale_systemd_service_name }}.target"
    - "{{ funkwhale_systemd_service_name }}-worker.service"
    - "{{ funkwhale_systemd_service_name }}-server.service"
    - "{{ funkwhale_systemd_service_name }}-beat.service"
