---
- name: restart funkwhale
  become: true
  service:
    name: "{{ funkwhale_systemd_service_name }}.target"
    state: restarted

- name: reload funkwhale
  become: true
  shell: |
    systemctl kill -s HUP {{ funkwhale_systemd_service_name }}-server
    systemctl kill -s HUP {{ funkwhale_systemd_service_name }}-worker
    systemctl restart {{ funkwhale_systemd_service_name }}-beat

- name: reload nginx
  become: true
  service:
    name: nginx
    state: reloaded
