---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  #flake8
platforms:
  - name: debian-buster
    image: alehaa/debian-systemd:buster
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  inventory:
    host_vars:
      debian-buster:
        ansible_python_interpreter: "/usr/bin/python3"

verifier:
  name: testinfra
