---
- name: Converge
  hosts: all
  roles:
    # our directory name is not "funkwhale" so molecule can't find the role
    # https://github.com/ansible/molecule/issues/1567#issuecomment-436876722
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
